spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tophut_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate_ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
